# Home Assistant Addon Configuration
name: "PostgreSQL MCP Server"
description: "Model Context Protocol server for PostgreSQL database access with authentication"
version: "1.3.4"
slug: "postgresql-mcp-server"
url: "https://github.com/jodur/mcp-addon-postgresql-homeassistant"
codenotary: "notary@home-assistant.io"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: manual
init: false
stage: stable
map:
  - "share:rw"
  - "ssl:rw"
  - "config:rw"
options:
  database_url: "postgresql://username:password@host:5432/database"
  server_port: 3000
  log_level: "info"
  max_connections: 10
  enable_write_operations: false
  ha_base_url: "http://supervisor/core"
schema:
  database_url: "str"
  server_port: "int(1000,65535)"
  log_level: "list(debug|info|warn|error)"
  max_connections: "int(1,100)"
  enable_write_operations: "bool"
  ha_base_url: "str"
ports:
  "3000/tcp": 3000
ports_description:
  "3000/tcp": "MCP Server HTTP Port"
# Note: Image will be built locally by Home Assistant
# For local addons, remove the image field to let HA build from Dockerfile
